/**
 THIS FILE IS CREATED BY TSIHANG FOR PCI/DEV SUPPORTED OF VENDORS.
*/
#ifndef __VENDORS_H__
#define __VENDORS_H__

/*
 * VirtIO PCI vendor/device ID. 
 */
#define VIRTIO_PCI_VENDOR_ID     0x1AF4
#define VIRTIO_PCI_DEVID_LEGACY_NET 0x1000
#define VIRTIO_PCI_DEVID_MODERN_NET 0x1041

/*
 * VMWARE vmxnet3 PCI vendor/device ID.
 */
#define VMWARE_PCI_VENDOR_ID 0x15AD
#define VMWARE_PCI_DEVID_VMXNET3 0x07B0


/* 
 * Intel PCI vendor/device ID. 
 */
#define E1000_INTEL_PCI_VENDOR_ID 0x8086


/* 
 * QAT crypto device ID within E1000 Intel PCI.
 */
#define E1000_INTEL_PCI_DEVID_QAT0	0x0443
#define E1000_INTEL_PCI_DEVID_QAT1	0x37C9
#define E1000_INTEL_PCI_DEVID_QAT2	0x19E3


#define CISCO_PCI_VENDOR_ID	0x1137
#define CISCO_PCI_DEVID_VIC_ENET	0x0043  /* ethernet vnic */
#define CISCO_PCI_DEVID_VIC_ENET_VF	0x0071  /* enet SRIOV VF */

#define CHELSIO_PCI_VENDOR_ID 0x1425


/* 
 * Cavium PCI vendor/device ID. 
 */
#define	CAVIUM_PCI_VENDOR_ID				0x177D
#define	CAVIUM_PCI_DEVID_THUNDERX_CN88XX_PASS1_NICVF	0x0011
#define CAVIUM_PCI_DEVID_THUNDERX_BGX			0xA026
#define	CAVIUM_PCI_DEVID_THUNDERX_NICVF				0xA034
#define	CAVIUM_PCI_SUBDEVID_CN88XX_PASS1_NICVF		0xA11E
#define	CAVIUM_PCI_SUBDEVID_CN88XX_PASS2_NICVF		0xA134
#define	CAVIUM_PCI_SUBDEVID_CN81XX_NICVF			0xA234
#define	CAVIUM_PCI_SUBDEVID_CN83XX_NICVF			0xA334


#endif

